import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Context_Provider } from "@/context/Context";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Inti-Tech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {
  return (
    <Context_Provider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </Context_Provider>

  );
}
