import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/helpers/clientLayout";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700", "500"],
});


export const metadata: Metadata = {
  title: "Inti-Tech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ClientLayout>
          {children}
        </ClientLayout>
        </body>
    </html>
  );
}
